apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "{{ include \"gitops-demo.fullname\" . }}-monitor"
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  namespaceSelector:
    matchNames:
      - production
  endpoints:
    - port: http
      path: /metrics
      interval: 15s