replicaCount: 2

image:
  tag: "53bc560f843c3c09fc7acc1ab8f790943cdd33fd"

ingress:
  host: api.gitops-demo.local

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi