replicaCount: 1

image:
  tag: "a41b486cc0cbe6474f576a4ad795fb255d1a4f11"

ingress:
  host: staging.gitops-demo.local

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi