replicaCount: 1

image:
  tag: "af19bf7de5d09a6f7550de2a80d38249c8589b03"

ingress:
  host: staging.gitops-demo.local

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi