replicaCount: 2

image:
  repository: abdo2400/gitops-demo
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  host: api.gitops-demo.local

livenessProbe:
  path: /health
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 15