replicaCount: 2

image:
  tag: "8b2b8dc88b800795e74eaafe7553d1db91bdc62a"

ingress:
  host: api.gitops-demo.local

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi