replicaCount: 1

image:
  tag: "563fe44143489a391f43f9d12c9080ed128d9c98"

ingress:
  host: staging.gitops-demo.local

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi