replicaCount: 2

image:
  repository: abdo2400/gitops-demo
  tag: "760ebbba8f5206fee796a2b5d4764af818aaceef"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 3000
  nodePort: 30080

livenessProbe:
  path: /health
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 15