replicaCount: 2

image:
  repository: abdo2400/gitops-demo
  tag: "dcb65ff8114f7151cefe0be9b2e629bfa60e4419"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 3000
  nodePort: 30080

livenessProbe:
  path: /health
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 15