replicaCount: 2

image:
  tag: "0e859f7554b5af5e238a374916e7d303d6a825d6"

ingress:
  host: api.gitops-demo.local

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi